/**
 * Created by wujiahui on 2018/9/17.
 */
// mock service
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/index';

@Injectable({
    providedIn: 'root'
})
export class StaffInfoMockService {

    constructor() {
    }

    mockListData(): Observable<[object]> {
        return Observable.create(observer => {
            observer.next([
                {
                    name: '我是姓名1',
                    staffId: '我是工号1',
                    position: '我是岗位1',
                    sysId: '我是角色1',
                    sysAccount: '我是账号1',
                    sysPwd: '我是密码1',
                    identification: '我是身份证1',
                    address: '我是住址1',
                    phone: '我是电话1',
                    urgentPerson: '我是紧急联系人1',
                    urgentPhone: '我是紧急联系人电话1',
                    email: '我是邮箱1',
                    remark: '我是备注1',
                },
                {
                    name: '我是姓名2',
                    staffId: '我是工号2',
                    position: '我是岗位2',
                    sysId: '我是角色2',
                    sysAccount: '我是账号2',
                    sysPwd: '我是密码2',
                    identification: '我是身份证2',
                    address: '我是住址2',
                    phone: '我是电话2',
                    urgentPerson: '我是紧急联系人2',
                    urgentPhone: '我是紧急联系人电话2',
                    email: '我是邮箱2',
                    remark: '我是备注2',
                },
                {
                    name: '我是姓名2',
                    staffId: '我是工号2',
                    position: '我是岗位2',
                    sysId: '我是角色2',
                    sysAccount: '我是账号2',
                    sysPwd: '我是密码2',
                    identification: '我是身份证2',
                    address: '我是住址2',
                    phone: '我是电话2',
                    urgentPerson: '我是紧急联系人2',
                    urgentPhone: '我是紧急联系人电话2',
                    email: '我是邮箱2',
                    remark: '我是备注2',
                },
                {
                    name: '我是姓名2',
                    staffId: '我是工号2',
                    position: '我是岗位2',
                    sysId: '我是角色2',
                    sysAccount: '我是账号2',
                    sysPwd: '我是密码2',
                    identification: '我是身份证2',
                    address: '我是住址2',
                    phone: '我是电话2',
                    urgentPerson: '我是紧急联系人2',
                    urgentPhone: '我是紧急联系人电话2',
                    email: '我是邮箱2',
                    remark: '我是备注2',
                },
                {
                    name: '我是姓名2',
                    staffId: '我是工号2',
                    position: '我是岗位2',
                    sysId: '我是角色2',
                    sysAccount: '我是账号2',
                    sysPwd: '我是密码2',
                    identification: '我是身份证2',
                    address: '我是住址2',
                    phone: '我是电话2',
                    urgentPerson: '我是紧急联系人2',
                    urgentPhone: '我是紧急联系人电话2',
                    email: '我是邮箱2',
                    remark: '我是备注2',
                },
                {
                    name: '我是姓名2',
                    staffId: '我是工号2',
                    position: '我是岗位2',
                    sysId: '我是角色2',
                    sysAccount: '我是账号2',
                    sysPwd: '我是密码2',
                    identification: '我是身份证2',
                    address: '我是住址2',
                    phone: '我是电话2',
                    urgentPerson: '我是紧急联系人2',
                    urgentPhone: '我是紧急联系人电话2',
                    email: '我是邮箱2',
                    remark: '我是备注2',
                },
                {
                    name: '我是姓名2',
                    staffId: '我是工号2',
                    position: '我是岗位2',
                    sysId: '我是角色2',
                    sysAccount: '我是账号2',
                    sysPwd: '我是密码2',
                    identification: '我是身份证2',
                    address: '我是住址2',
                    phone: '我是电话2',
                    urgentPerson: '我是紧急联系人2',
                    urgentPhone: '我是紧急联系人电话2',
                    email: '我是邮箱2',
                    remark: '我是备注2',
                },
                {
                    name: '我是姓名2',
                    staffId: '我是工号2',
                    position: '我是岗位2',
                    sysId: '我是角色2',
                    sysAccount: '我是账号2',
                    sysPwd: '我是密码2',
                    identification: '我是身份证2',
                    address: '我是住址2',
                    phone: '我是电话2',
                    urgentPerson: '我是紧急联系人2',
                    urgentPhone: '我是紧急联系人电话2',
                    email: '我是邮箱2',
                    remark: '我是备注2',
                },
                {
                    name: '我是姓名2',
                    staffId: '我是工号2',
                    position: '我是岗位2',
                    sysId: '我是角色2',
                    sysAccount: '我是账号2',
                    sysPwd: '我是密码2',
                    identification: '我是身份证2',
                    address: '我是住址2',
                    phone: '我是电话2',
                    urgentPerson: '我是紧急联系人2',
                    urgentPhone: '我是紧急联系人电话2',
                    email: '我是邮箱2',
                    remark: '我是备注2',
                },
                {
                    name: '我是姓名2',
                    staffId: '我是工号2',
                    position: '我是岗位2',
                    sysId: '我是角色2',
                    sysAccount: '我是账号2',
                    sysPwd: '我是密码2',
                    identification: '我是身份证2',
                    address: '我是住址2',
                    phone: '我是电话2',
                    urgentPerson: '我是紧急联系人2',
                    urgentPhone: '我是紧急联系人电话2',
                    email: '我是邮箱2',
                    remark: '我是备注2',
                },
                {
                    name: '我是姓名2',
                    staffId: '我是工号2',
                    position: '我是岗位2',
                    sysId: '我是角色2',
                    sysAccount: '我是账号2',
                    sysPwd: '我是密码2',
                    identification: '我是身份证2',
                    address: '我是住址2',
                    phone: '我是电话2',
                    urgentPerson: '我是紧急联系人2',
                    urgentPhone: '我是紧急联系人电话2',
                    email: '我是邮箱2',
                    remark: '我是备注2',
                },
                {
                    name: '我是姓名2',
                    staffId: '我是工号2',
                    position: '我是岗位2',
                    sysId: '我是角色2',
                    sysAccount: '我是账号2',
                    sysPwd: '我是密码2',
                    identification: '我是身份证2',
                    address: '我是住址2',
                    phone: '我是电话2',
                    urgentPerson: '我是紧急联系人2',
                    urgentPhone: '我是紧急联系人电话2',
                    email: '我是邮箱2',
                    remark: '我是备注2',
                },
                {
                    name: '我是姓名2',
                    staffId: '我是工号2',
                    position: '我是岗位2',
                    sysId: '我是角色2',
                    sysAccount: '我是账号2',
                    sysPwd: '我是密码2',
                    identification: '我是身份证2',
                    address: '我是住址2',
                    phone: '我是电话2',
                    urgentPerson: '我是紧急联系人2',
                    urgentPhone: '我是紧急联系人电话2',
                    email: '我是邮箱2',
                    remark: '我是备注2',
                },
                {
                    name: '我是姓名2',
                    staffId: '我是工号2',
                    position: '我是岗位2',
                    sysId: '我是角色2',
                    sysAccount: '我是账号2',
                    sysPwd: '我是密码2',
                    identification: '我是身份证2',
                    address: '我是住址2',
                    phone: '我是电话2',
                    urgentPerson: '我是紧急联系人2',
                    urgentPhone: '我是紧急联系人电话2',
                    email: '我是邮箱2',
                    remark: '我是备注2',
                },
                {
                    name: '我是姓名2',
                    staffId: '我是工号2',
                    position: '我是岗位2',
                    sysId: '我是角色2',
                    sysAccount: '我是账号2',
                    sysPwd: '我是密码2',
                    identification: '我是身份证2',
                    address: '我是住址2',
                    phone: '我是电话2',
                    urgentPerson: '我是紧急联系人2',
                    urgentPhone: '我是紧急联系人电话2',
                    email: '我是邮箱2',
                    remark: '我是备注2',
                },
                {
                    name: '我是姓名2',
                    staffId: '我是工号2',
                    position: '我是岗位2',
                    sysId: '我是角色2',
                    sysAccount: '我是账号2',
                    sysPwd: '我是密码2',
                    identification: '我是身份证2',
                    address: '我是住址2',
                    phone: '我是电话2',
                    urgentPerson: '我是紧急联系人2',
                    urgentPhone: '我是紧急联系人电话2',
                    email: '我是邮箱2',
                    remark: '我是备注2',
                },
            ]);
        });
    }
}
